import assert from 'node:assert/strict';
const base=process.argv[2]||'http://localhost:3000';
let passed=0;
const ok=(name,condition)=>{assert.ok(condition,name);passed++;console.log('✓ '+name);};
function client(cookie=''){return {cookie,async request(method,payload){const r=await fetch(base+'/api/game'+(method==='GET'&&payload?'?room='+payload:''),{method,headers:{...(this.cookie?{cookie:this.cookie}:{}),...(method==='POST'?{'Content-Type':'application/json'}:{})},...(method==='POST'?{body:JSON.stringify(payload)}:{})});const set=r.headers.get('set-cookie');if(set)this.cookie=set.split(';')[0];return {status:r.status,data:await r.json(),headers:r.headers};}};}
const red=client(),black=client(),watcher=client();
const session=await red.request('GET');ok('初始化匿名身份',session.status===200&&red.cookie.length>40);ok('身份 Cookie 禁止脚本读取',session.headers.get('set-cookie')?.includes('HttpOnly'));
let result=await red.request('POST',{action:'create',name:'联机测试红方',clockMinutes:0});assert.equal(result.status,200,JSON.stringify(result.data));let state=result.data;const id=state.id;
ok('创建持久化好友棋室',state.you==='red'&&state.players.black===null);
ok('未泄露座位身份凭证',!JSON.stringify(state).includes('secret')&&!('id'in state.players.red));
let viewed=await black.request('GET',id);ok('邀请链接可从独立身份打开',viewed.status===200&&viewed.data.id===id&&viewed.data.you===null);
result=await black.request('POST',{action:'join',room:id,version:state.version,name:'联机测试黑方'});assert.equal(result.status,200,JSON.stringify(result.data));state=result.data;ok('好友加入执黑，双方开始',state.you==='black'&&state.players.black.name==='联机测试黑方');
viewed=await red.request('GET',id);ok('红方收到入座同步',viewed.data.players.black.name==='联机测试黑方'&&viewed.data.you==='red');
const send=async(who,action,extra={})=>{const r=await who.request('POST',{action,room:id,version:state.version,...extra});if(r.status===200)state=r.data;return r;};
result=await send(black,'move',{from:27,to:36});ok('服务器阻止越回合落子',result.status===400);
result=await send(red,'move',{from:54,to:45});ok('红方合法落子已存储',result.status===200&&state.history.length===1&&state.board[45]?.kind==='p');
viewed=await black.request('GET',id);ok('对手看到同一棋盘',viewed.data.board[45]?.side==='red'&&viewed.data.turn==='black');
result=await send(black,'move',{from:27,to:36});ok('黑方合法落子',result.status===200&&state.history.length===2);
result=await send(red,'undo');ok('红方无需同意撤回黑方一步',result.status===200&&state.history.length===1&&state.turn==='black');
result=await send(black,'undo');ok('黑方无需同意撤回红方一步',result.status===200&&state.history.length===0&&state.turn==='red');
viewed=await watcher.request('GET',id);ok('第三人只能观战',viewed.data.you===null&&viewed.data.players.black!==null);
result=await send(watcher,'move',{from:54,to:45});ok('服务器拒绝观战者落子',result.status===403);
result=await send(watcher,'undo');ok('服务器拒绝观战者悔棋',result.status===403);
result=await send(watcher,'join',{name:'第三人'});ok('已占座位不能被抢占',result.status===409);
result=await red.request('POST',{action:'move',room:id,version:0,from:54,to:45});ok('过期版本请求不会覆盖新棋局',result.status===409);
const concurrent=await Promise.all([red.request('POST',{action:'move',room:id,version:state.version,from:54,to:45}),red.request('POST',{action:'move',room:id,version:state.version,from:56,to:47})]);ok('同时落子只接受一步',concurrent.filter(r=>r.status===200).length===1&&concurrent.filter(r=>r.status===409).length===1);state=concurrent.find(r=>r.status===200).data;
viewed=await client(red.cookie).request('GET',id);ok('刷新后恢复座位和棋局',viewed.data.you==='red'&&viewed.data.history.length===1);
result=await send(black,'chat',{text:'测试消息：好棋！'});ok('聊天发送并持久化',result.status===200&&state.chat.at(-1).text==='测试消息：好棋！');
viewed=await red.request('GET',id);ok('聊天对手同步',viewed.data.chat.at(-1).side==='black');
result=await send(red,'offer-draw');ok('提和进入待回应状态',result.status===200&&state.offer.kind==='draw');
result=await send(black,'respond',{accept:false});ok('对方可拒绝提和',result.status===200&&state.offer===null&&state.result===null);
await send(black,'offer-draw');result=await send(red,'respond',{accept:true});ok('双方同意才结束为和棋',result.status===200&&state.result.winner==='draw');
result=await send(black,'undo');ok('终局后仍可悔棋恢复',result.status===200&&state.result===null&&state.history.length===0);
result=await send(red,'resign');ok('认输判对手获胜',result.status===200&&state.result.winner==='black');
await send(red,'offer-rematch');result=await send(black,'respond',{accept:true});ok('再来一局交换先后手',result.status===200&&state.you==='red'&&state.round===2&&state.history.length===0);
viewed=await red.request('GET',id);ok('原红方收到换边状态',viewed.data.you==='black');
result=await send(red,'name',{name:'更名后的棋友'});ok('称呼修改同步',result.status===200&&state.players.black.name==='更名后的棋友');
const attack=await fetch(base+'/api/game',{method:'POST',headers:{'Content-Type':'application/json',cookie:red.cookie,origin:'https://unrelated.example'},body:JSON.stringify({action:'resign',room:id,version:state.version})});ok('跨站操作被拒绝',attack.status===403);
const bad=await red.request('GET','invalid');ok('错误邀请链接给出明确错误',bad.status===404&&bad.data.error.includes('链接'));
console.log(`\n${passed} online checks passed. Room ${id}`);
