import assert from 'node:assert/strict';
import { identity, validateRequestOrigin, corsResponse, preflight, pagesOrigin } from '../lib/request-identity';
import { invitationUrl } from '../lib/client-api';
import { readFileSync } from 'node:fs';
const backend = 'https://chuhan-friends-xiangqi.zhanglushan1.chatgpt.site';
let checks = 0;
async function test(name: string, fn: () => unknown | Promise<unknown>) { await fn(); checks++; console.log('✓ '+name); }
const token = 'a'.repeat(64);
const request = (headers: Record<string,string> = {}, method = 'GET') => new Request(backend+'/api/game', { method, headers });
await test('Github 项目邀请链接保留项目路径', () => assert.equal(invitationUrl(pagesOrigin, '/chuhan-xiangqi/', 'abc'), pagesOrigin+'/chuhan-xiangqi/?room=abc'));
await test('现有网站邀请链接仍指向根路径', () => assert.equal(invitationUrl(backend, '/', 'abc'), backend+'/?room=abc'));
await test('同源浏览器继续允许 Cookie 身份', () => validateRequestOrigin(request({Origin:backend,'Sec-Fetch-Site':'same-origin'})));
await test('原 Cookie 身份刷新后保持不变', async () => { const first=await identity(request()); assert(first.cookie.includes('HttpOnly')); const second=await identity(request({Cookie:first.cookie.split(';')[0]})); assert.equal(first.id,second.id); assert.equal(second.cookie,''); });
await test('GitHub 玩家带座位凭证可以访问', () => validateRequestOrigin(request({Origin:pagesOrigin,'X-Chuhan-Session':token,'Sec-Fetch-Site':'cross-site'})));
await test('GitHub 玩家刷新保持身份且不使用第三方 Cookie', async () => { const r=request({Origin:pagesOrigin,'X-Chuhan-Session':token}); const a=await identity(r),b=await identity(r); assert.equal(a.id,b.id); assert.equal(a.cookie,''); assert.notEqual(a.id,token); });
await test('不同玩家凭证不能互相占座', async () => assert.notEqual((await identity(request({'X-Chuhan-Session':token}))).id,(await identity(request({'X-Chuhan-Session':'b'.repeat(64)}))).id));
await test('跨域显式凭证优先于后台站点 Cookie', async () => { const a=await identity(request({'X-Chuhan-Session':token,Cookie:'chuhan_session='+'b'.repeat(64)})),b=await identity(request({'X-Chuhan-Session':token}));assert.equal(a.id,b.id); });
await test('拒绝 GitHub 页面仅携带环境 Cookie 操作', () => assert.throws(()=>validateRequestOrigin(request({Origin:pagesOrigin,Cookie:'chuhan_session='+token}))));
await test('拒绝伪造相似 GitHub 域名', () => assert.throws(()=>validateRequestOrigin(request({Origin:'https://xsgzls711.github.io.evil.example','X-Chuhan-Session':token}))));
await test('拒绝其他 GitHub 账号来源', () => assert.throws(()=>validateRequestOrigin(request({Origin:'https://unrelated.github.io','X-Chuhan-Session':token}))));
await test('拒绝未指定受信任来源的跨站请求', () => assert.throws(()=>validateRequestOrigin(request({'Sec-Fetch-Site':'cross-site','X-Chuhan-Session':token}))));
await test('拒绝格式错误的座位凭证', async () => { await assert.rejects(()=>identity(request({'X-Chuhan-Session':'short'}))); });
await test('允许正确的跨域预检', () => { const r=preflight(request({Origin:pagesOrigin,'Access-Control-Request-Method':'POST','Access-Control-Request-Headers':'content-type,x-chuhan-session'},'OPTIONS')); assert.equal(r.status,204);assert.equal(r.headers.get('access-control-allow-origin'),pagesOrigin);assert.equal(r.headers.get('access-control-allow-credentials'),null); });
await test('拒绝其他域名的跨域预检', () => assert.equal(preflight(request({Origin:'https://unrelated.example','Access-Control-Request-Method':'POST'},'OPTIONS')).status,403));
await test('拒绝额外的方法和请求头', () => { assert.equal(preflight(request({Origin:pagesOrigin,'Access-Control-Request-Method':'DELETE'},'OPTIONS')).status,403); assert.equal(preflight(request({Origin:pagesOrigin,'Access-Control-Request-Method':'POST','Access-Control-Request-Headers':'Authorization'},'OPTIONS')).status,403); });
await test('成功与错误回复均允许指定网页读取', () => { for (const status of [200,400,401,409]) {const r=corsResponse(request({Origin:pagesOrigin}),new Response('body',{status}));assert.equal(r.headers.get('Access-Control-Allow-Origin'),pagesOrigin);assert.equal(r.status,status);} });
await test('未知来源回复没有跨域授权', () => assert.equal(corsResponse(request({Origin:'https://unrelated.example'}),new Response()).headers.get('Access-Control-Allow-Origin'),null));
await test('页面全部联机请求使用统一跨域客户端', () => {const source=readFileSync('app/page.tsx','utf8');assert(!/\bfetch\('/.test(source));assert(!source.includes('href="/"'));assert(source.includes('invitationUrl(location.origin,location.pathname,room.id)'));});
console.log(`\n${checks} Pages migration checks passed`);
