import assert from 'node:assert/strict';
import {initialBoard,legalMove,legalTargets,moveBoard,pseudoLegal,inCheck,hasLegalMove,notation,opposite,outcome,type Board,type Side,type Kind} from '../lib/xiangqi';
import {newRoom,applyAction,expireClock,playerSide} from '../lib/game';
let count=0;const test=(name:string,fn:()=>void)=>{fn();count++;console.log('✓ '+name);};
function setup(pieces:[number,Side,Kind][]):Board{const b:Board=Array(90).fill(null);for(const [i,side,kind]of pieces)b[i]={side,kind,id:String(i)};return b;}
const b=initialBoard();
test('初始棋盘有 32 枚棋子',()=>assert.equal(b.filter(Boolean).length,32));
test('开局红方恰有 44 种合法走法',()=>assert.equal(b.reduce((n,p,i)=>n+(p?.side==='red'?legalTargets(b,i).length:0),0),44));
function perft(b:Board,side:Side,depth:number):number{if(!depth)return 1;let total=0;for(let i=0;i<90;i++)if(b[i]?.side===side)for(const j of legalTargets(b,i))total+=perft(moveBoard(b,i,j),opposite(side),depth-1);return total;}
test('开局第二层走法总数为 1920',()=>assert.equal(perft(b,'red',2),1920));
test('开局第三层走法总数为 79666',()=>assert.equal(perft(b,'red',3),79666));
test('马腿被挡不可跳',()=>assert.equal(pseudoLegal(setup([[82,'red','h'],[73,'red','p']]),82,63),false));
test('马可正常跳出',()=>assert(legalMove(b,82,63,'red')));
test('象眼阻挡',()=>assert.equal(pseudoLegal(setup([[83,'red','e'],[75,'red','p']]),83,67),false));
test('象不得过河',()=>assert.equal(pseudoLegal(setup([[47,'red','e']]),47,31),false));
test('象可退回',()=>assert(pseudoLegal(setup([[47,'red','e']]),47,67)));
test('士不得离开九宫',()=>assert.equal(pseudoLegal(setup([[66,'red','a']]),66,56),false));
test('帅不得离开九宫',()=>assert.equal(pseudoLegal(setup([[66,'red','k']]),66,65),false));
test('兵未过河不可横走',()=>assert.equal(pseudoLegal(b,54,55),false));
test('兵过河可横走不可后退',()=>{const x=setup([[36,'red','p']]);assert(pseudoLegal(x,36,37));assert.equal(pseudoLegal(x,36,45),false);});
test('黑卒方向正确',()=>{assert(pseudoLegal(b,27,36));assert.equal(pseudoLegal(b,27,18),false);});
test('炮隔一子吃子',()=>assert(pseudoLegal(b,64,1)));
test('炮不能无架吃子',()=>assert.equal(pseudoLegal(setup([[64,'red','c'],[1,'black','h']]),64,1),false));
test('炮不能隔两子吃子',()=>assert.equal(pseudoLegal(setup([[64,'red','c'],[1,'black','h'],[28,'red','p'],[37,'black','p']]),64,1),false));
test('车不可穿子',()=>assert.equal(pseudoLegal(b,81,0),false));
test('己方棋子不可互吃',()=>assert.equal(pseudoLegal(b,81,82),false));
test('将帅照面会构成将军',()=>assert(inCheck(setup([[4,'black','k'],[85,'red','k']]),'red')));
test('露出将帅照面的走法非法',()=>assert.equal(legalMove(setup([[4,'black','k'],[85,'red','k'],[49,'red','r']]),49,48,'red'),false));
test('不得将自己暴露在车口',()=>assert.equal(legalMove(setup([[3,'black','k'],[85,'red','k'],[4,'black','r'],[76,'red','r']]),76,75,'red'),false));
test('异常坐标被拒绝',()=>{for(const p of [NaN,undefined,-1,90,3.5,'4'])assert.equal(legalMove(b,p as number,40,'red'),false);});
test('中文棋谱炮二平五',()=>assert.equal(notation(b,70,67),'炮二平五'));
test('将死正确判负',()=>{const x=setup([[4,'black','k'],[85,'red','k'],[13,'red','r'],[21,'red','r'],[23,'red','r']]);assert(inCheck(x,'black'));assert.equal(hasLegalMove(x,'black'),false);assert.equal(outcome(x,'black',[],0)?.winner,'red');});
test('困毙正确判负',()=>{const x=setup([[4,'black','k'],[86,'red','k'],[12,'red','r'],[14,'red','r']]);assert.equal(inCheck(x,'black'),false);assert.equal(hasLegalMove(x,'black'),false);assert.equal(outcome(x,'black',[],0)?.reason,'困毙');});
const now=100000,red='secret-red',black='secret-black';const fresh=(clock=0)=>{const r=newRoom('test',{id:red,name:'红棋友'},clock,now);applyAction(r,black,{action:'join',name:'黑棋友'},now);return r;};
test('身份正确且旁观者无法操作',()=>{const r=fresh();assert.equal(playerSide(r,red),'red');assert.throws(()=>applyAction(r,'spectator',{action:'resign'},now));});
test('不能抢占已满的座位',()=>assert.throws(()=>applyAction(fresh(),'third',{action:'join'},now)));
test('黑方不能抢先落子',()=>assert.throws(()=>applyAction(fresh(),black,{action:'move',from:27,to:36},now)));
test('任意一方可撤回对方上一步且不限次数',()=>{const r=fresh();for(let i=0;i<12;i++){applyAction(r,red,{action:'move',from:54,to:45},now);applyAction(r,black,{action:'undo'},now);assert.deepEqual(r.board,b);assert.equal(r.turn,'red');assert.equal(r.history.length,0);}});
test('计时落子扣时，悔棋恢复用时',()=>{const r=fresh(10);applyAction(r,red,{action:'move',from:54,to:45},now+15000);assert.equal(r.clocks.red,585000);applyAction(r,black,{action:'undo'},now+30000);assert.equal(r.clocks.red,600000);assert.equal(r.turnAt,now+30000);});
test('吃子后悔棋恢复双方棋子与历史',()=>{const r=fresh();for(const [id,from,to]of [[red,64,1],[black,0,1]] as [string,number,number][])applyAction(r,id,{action:'move',from,to},now);applyAction(r,red,{action:'undo'},now);assert.equal(r.board[1]?.kind,'c');assert.equal(r.board[0]?.kind,'r');applyAction(r,black,{action:'undo'},now);assert.deepEqual(r.board,b);});
test('认输与结束后悔棋继续',()=>{const r=fresh();applyAction(r,red,{action:'move',from:54,to:45},now);applyAction(r,black,{action:'resign'},now);assert.equal(r.result?.winner,'red');applyAction(r,red,{action:'undo'},now);assert.equal(r.result,null);assert.deepEqual(r.board,b);});
test('零步认输后也可撤回继续',()=>{const r=fresh();applyAction(r,red,{action:'resign'},now);applyAction(r,black,{action:'undo'},now);assert.equal(r.result,null);});
test('不能同意自己提和，对方同意才和棋',()=>{const r=fresh();applyAction(r,red,{action:'offer-draw'},now);assert.throws(()=>applyAction(r,red,{action:'respond',accept:true},now));applyAction(r,black,{action:'respond',accept:true},now);assert.equal(r.result?.winner,'draw');});
test('拒绝和棋后继续，走棋撤回提和',()=>{const r=fresh();applyAction(r,red,{action:'offer-draw'},now);applyAction(r,black,{action:'respond',accept:false},now);assert.equal(r.offer,null);applyAction(r,red,{action:'offer-draw'},now);applyAction(r,red,{action:'move',from:54,to:45},now);assert.equal(r.offer,null);});
test('重开需双方同意并交换红黑',()=>{const r=fresh();applyAction(r,red,{action:'offer-rematch'},now);assert.equal(r.round,1);applyAction(r,black,{action:'respond',accept:true},now+1000);assert.equal(r.round,2);assert.equal(r.players.red.id,black);assert.equal(r.players.black?.id,red);assert.deepEqual(r.board,b);});
test('时钟超时仅判当前方负，未入座不计时',()=>{const r=fresh(10);assert(expireClock(r,now+600000));assert.equal(r.result?.winner,'black');assert.equal(expireClock(newRoom('x',{id:red,name:'红'},10,now),now+900000),false);});
test('不限时对局不会超时',()=>assert.equal(expireClock(fresh(),now+999999999),false));
test('三次重复局面判和',()=>{const r=fresh();for(let i=0;i<2;i++)for(const [id,from,to]of [[red,82,63],[black,1,18],[red,63,82],[black,18,1]] as [string,number,number][])applyAction(r,id,{action:'move',from,to},now);assert.equal(r.result?.reason,'三次重复局面');});
test('单方循环长将判负',()=>{const x=setup([[4,'black','k'],[85,'red','k'],[49,'red','p'],[12,'red','r']]);const history=Array.from({length:4},(_,i)=>({before:x,side:(i%2?'black':'red') as Side,check:i%2===0,from:12,to:13,text:'测试',captured:null,clocks:{red:0,black:0},quietBefore:0}));assert.equal(outcome(x,'red',history,4)?.winner,'black');});
test('连续 60 回合不吃子自动和棋',()=>assert.equal(outcome(b,'red',[],120)?.reason,'连续 60 回合未吃子'));
test('推演不修改正式棋盘',()=>{const r=fresh();const copy=moveBoard(r.board,54,45);assert.notDeepEqual(copy,r.board);assert.deepEqual(r.board,b);});
console.log(`\n${count} checks passed`);
